[package]
name = "portfolio-game"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = { version = "0.4.14", features = ["audio"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
